
#name: A workflow for my Hello World file
#on: push
#
#jobs:
#  build:
#    name: Hello world action
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: ./action-a
#        with:
#          MY_NAME: "Mona"



name: Run terraform
on: push

jobs:
  tfe:
    name: run tfe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform validate
